# Generated by Django 5.0.1 on 2024-01-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_cancel',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_check_out',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
