# Generated by Django 5.0.1 on 2024-01-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('*', '1 star'), ('**', '2 stars'), ('***', '3 stars'), ('****', '4 stars'), ('*****', '5 stars')], max_length=6),
        ),
    ]
