# Generated by Django 5.0.1 on 2024-01-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='account_no',
            field=models.IntegerField(),
        ),
    ]
