# Generated by Django 5.0.1 on 2024-04-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='default_image.png', upload_to='student/media/images'),
        ),
    ]
